### ISSUE TITLE
convert_to_image.py <input_path> <output_path>

### ISSUE THREAD

**Issue by nitrlegend** [abdoofathy95/EMNIST-binary-To-PNG#1]

**Comment by nitrlegend** [comment]
I cant understand why this issue is popping up on running the above code

**Comment by abdoofathy95** [comment]
what's the issue?

**Comment by nitrlegend** [comment]
This was the message that i was getting after after writing the code python convert_to_image.py.Apparantly i forgot to give the input and output path.However it is sorted now.
